// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebSite.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20260715115438_ChangeModels")]
    partial class ChangeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebSite.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValidityPeriod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("WebSite.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpertAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("WebSite.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("WebSite.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WebSite.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("WebSite.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DepositPrice")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MortgagePrice")
                        .HasColumnType("float");

                    b.Property<double?>("PreSalePrice")
                        .HasColumnType("float");

                    b.Property<double?>("RentPrice")
                        .HasColumnType("float");

                    b.Property<double?>("SalePrice")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deal");
                });

            modelBuilder.Entity("WebSite.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrightnessLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cabbie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CommercialArea")
                        .HasColumnType("float");

                    b.Property<string>("CoolingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElectricityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Elevator")
                        .HasColumnType("int");

                    b.Property<string>("FloorCovering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GasType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Infrastructure")
                        .HasColumnType("float");

                    b.Property<double?>("KitchenArea")
                        .HasColumnType("float");

                    b.Property<string>("LandlineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LivingRoomArea")
                        .HasColumnType("float");

                    b.Property<int?>("Numberofkitchens")
                        .HasColumnType("int");

                    b.Property<string>("OtherFacilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParkingCount")
                        .HasColumnType("int");

                    b.Property<string>("PrivateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<string>("Staircase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WCArea")
                        .HasColumnType("float");

                    b.Property<int?>("WCCount")
                        .HasColumnType("int");

                    b.Property<string>("Wardrobe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("YardArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("WebSite.Models.Floor_RoomRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomId");

                    b.ToTable("Floor_RoomRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WebSite.Models.Location_CityRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LocationId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Location_CityRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Neighborhood");
                });

            modelBuilder.Entity("WebSite.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AggregationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Area")
                        .HasColumnType("float");

                    b.Property<string>("CertificateType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Expandable")
                        .HasColumnType("bit");

                    b.Property<string>("FacadeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeographicalLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("InputSeparate")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeadlock")
                        .HasColumnType("bit");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PassageWidth")
                        .HasColumnType("float");

                    b.Property<string>("PrivateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Renovated")
                        .HasColumnType("bit");

                    b.Property<int?>("Retreat")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("WebSite.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyImage");
                });

            modelBuilder.Entity("WebSite.Models.Property_Advertisement_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvertisementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_Advertisement_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_Applicant_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_Applicant_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_Deal_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_Deal_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_Location_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Property_Location_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_PropertyImage_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyImageId");

                    b.ToTable("Property_PropertyImage_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_Supplier_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Property_Supplier_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Property_Tag_FloorRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FloorId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TagId");

                    b.ToTable("Property_Tag_FloorRelation", (string)null);
                });

            modelBuilder.Entity("WebSite.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("WebSite.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoolingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Length")
                        .HasColumnType("float");

                    b.Property<string>("PrivateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomArea")
                        .HasColumnType("int");

                    b.Property<string>("Wardrobe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.Property<int?>("WindowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WebSite.Models.StaticData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BestCountOfNumber")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ImageAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringContentAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringContentFa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("StaticDatas");
                });

            modelBuilder.Entity("WebSite.Models.StaticDataGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StaticDataGroups");
                });

            modelBuilder.Entity("WebSite.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("WebSite.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("WebSite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebSite.Models.Floor_RoomRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("RoomRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Room", "Room")
                        .WithMany("FloorRelations")
                        .HasForeignKey("RoomId");

                    b.Navigation("Floor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebSite.Models.Location_CityRelation", b =>
                {
                    b.HasOne("WebSite.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("WebSite.Models.Location", "Location")
                        .WithMany("CityRelations")
                        .HasForeignKey("LocationId");

                    b.HasOne("WebSite.Models.Neighborhood", "Neighborhood")
                        .WithMany()
                        .HasForeignKey("NeighborhoodId");

                    b.HasOne("WebSite.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("City");

                    b.Navigation("Location");

                    b.Navigation("Neighborhood");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("WebSite.Models.Property_Advertisement_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Advertisement", "Advertisement")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("AdvertisementId");

                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("AdvertisementRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("AdvertisementRelations")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Advertisement");

                    b.Navigation("Floor");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("WebSite.Models.Property_Applicant_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Applicant", "Applicant")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("ApplicantId");

                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("ApplicantRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("ApplicantRelations")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Applicant");

                    b.Navigation("Floor");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("WebSite.Models.Property_Deal_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Deal", "Deal")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("DealId");

                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("DealRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("DealRelations")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Deal");

                    b.Navigation("Floor");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("WebSite.Models.Property_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("FloorRelations")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Floor");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("WebSite.Models.Property_Location_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("LocationRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("LocationRelations")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Floor");

                    b.Navigation("Location");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("WebSite.Models.Property_PropertyImage_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("PropertyImageRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("PropertyImageRelations")
                        .HasForeignKey("PropertyId");

                    b.HasOne("WebSite.Models.PropertyImage", "PropertyImage")
                        .WithMany("PropertyRelations")
                        .HasForeignKey("PropertyImageId");

                    b.Navigation("Floor");

                    b.Navigation("Property");

                    b.Navigation("PropertyImage");
                });

            modelBuilder.Entity("WebSite.Models.Property_Supplier_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("SupplierRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("SupplierRelations")
                        .HasForeignKey("PropertyId");

                    b.HasOne("WebSite.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Floor");

                    b.Navigation("Property");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebSite.Models.Property_Tag_FloorRelation", b =>
                {
                    b.HasOne("WebSite.Models.Floor", "Floor")
                        .WithMany("TagRelations")
                        .HasForeignKey("FloorId");

                    b.HasOne("WebSite.Models.Property", "Property")
                        .WithMany("TagRelations")
                        .HasForeignKey("PropertyId");

                    b.HasOne("WebSite.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");

                    b.Navigation("Floor");

                    b.Navigation("Property");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebSite.Models.StaticData", b =>
                {
                    b.HasOne("WebSite.Models.StaticDataGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebSite.Models.Advertisement", b =>
                {
                    b.Navigation("PropertyRelations");
                });

            modelBuilder.Entity("WebSite.Models.Applicant", b =>
                {
                    b.Navigation("PropertyRelations");
                });

            modelBuilder.Entity("WebSite.Models.Deal", b =>
                {
                    b.Navigation("PropertyRelations");
                });

            modelBuilder.Entity("WebSite.Models.Floor", b =>
                {
                    b.Navigation("AdvertisementRelations");

                    b.Navigation("ApplicantRelations");

                    b.Navigation("DealRelations");

                    b.Navigation("LocationRelations");

                    b.Navigation("PropertyImageRelations");

                    b.Navigation("PropertyRelations");

                    b.Navigation("RoomRelations");

                    b.Navigation("SupplierRelations");

                    b.Navigation("TagRelations");
                });

            modelBuilder.Entity("WebSite.Models.Location", b =>
                {
                    b.Navigation("CityRelations");
                });

            modelBuilder.Entity("WebSite.Models.Property", b =>
                {
                    b.Navigation("AdvertisementRelations");

                    b.Navigation("ApplicantRelations");

                    b.Navigation("DealRelations");

                    b.Navigation("FloorRelations");

                    b.Navigation("LocationRelations");

                    b.Navigation("PropertyImageRelations");

                    b.Navigation("SupplierRelations");

                    b.Navigation("TagRelations");
                });

            modelBuilder.Entity("WebSite.Models.PropertyImage", b =>
                {
                    b.Navigation("PropertyRelations");
                });

            modelBuilder.Entity("WebSite.Models.Room", b =>
                {
                    b.Navigation("FloorRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
