namespace WebSite.Models;
// نگهداری اطلاعات و شرایط موردنظر متقاضی برای جستجو و تطبیق ملک

public class Applicant
{
    public string Id { get; set; }
    public int Row { get; set; }
    public string? AddressBookId { get; set; }
    public string? PropertyId { get; set; }
    public short? Population { get; set; }
    public int? LocationId { get; set; }
    public string? Areas { get; set; }
    public string? PropertyTypes { get; set; }
    public string? UsageTypes { get; set; }
    public int LastModified { get; set; }
    public int LastManualUpdate { get; set; }
    public int LastSyncDate { get; set; }
    public int MinSpace { get; set; }
    public int MaxSpace { get; set; }
    public int MinInfrastructure { get; set; }
    public int MaxInfrastructure { get; set; }
    public long? MinSalePrice { get; set; }
    public long? MaxSalePrice { get; set; }
    public long? MinLoanPrice { get; set; }
    public long? MaxLoanPrice { get; set; }
    public long? MinMortgagePrice { get; set; }
    public long? MaxMortgagePrice { get; set; }
    public long? MinRentPrice { get; set; }
    public long? MaxRentPrice { get; set; }
    public bool ShortTermRent { get; set; }
    public string? CertificateType { get; set; }
    public string? Dongs { get; set; }
    public string? Aggregation { get; set; }
    public string RentPrefer { get; set; }
    public long? MinPresalePrice { get; set; }
    public long? MaxPresalePrice { get; set; }
    public long? MinPrepayValue { get; set; }
    public long? MaxPrepayValue { get; set; }
    public int? MaxDeliveryDate { get; set; }
    public bool RequestSale { get; set; }
    public bool RequestRent { get; set; }
    public bool RequestPreSale { get; set; }
    public bool RequestExchange { get; set; }
    public bool RequestAssociate { get; set; }
    public string? EstateStatus { get; set; }
    public string? Water { get; set; }
    public string? Electricity { get; set; }
    public string? Gas { get; set; }
    public string? Phone { get; set; }
    public string? Direction { get; set; }
    public string? PropertyAge { get; set; }
    public int? MaxPropertyAgeYear { get; set; }
    public int? MinPropertyAgeYear { get; set; }
    public short? MinRoomsCount { get; set; }
    public short MinStreetSpace { get; set; }
    public bool Elevator { get; set; }
    public bool Parking { get; set; }
    public bool Store { get; set; }
    public int? RegisterDate { get; set; }
    public int? PeriodInDays { get; set; }
    public int? ComeInSearchResult { get; set; }
    public int ComeInSearchResultInWebsite { get; set; }
    public int? DetailsSeenCount { get; set; }
    public int DetailsSeenCountInWebsite { get; set; }
    public string? Description { get; set; }
    public string? RegistrarAgency { get; set; }
    public string? RegistrarUser { get; set; }
    public bool MustHaveLoan { get; set; }
    public string? Priority1 { get; set; }
    public string? Priority2 { get; set; }
    public string? Priority3 { get; set; }
    public string? Priority4 { get; set; }
    public int? MatchPercent { get; set; }
    public bool OwnerShouldNotResident { get; set; }
    public bool IsNotImpasse { get; set; }
    public bool Yard { get; set; }
    public bool Elec3Phase { get; set; }
    public bool InputSeparate { get; set; }
    public bool MustHaveCommercial { get; set; }
    public string? ReservedField { get; set; }
    public bool IsArchived { get; set; }
    public bool ApplicantCanceled { get; set; }
    public bool IgnoreWebSite { get; set; }
    public bool DoneTransact { get; set; }
    public bool IsConfirmed { get; set; }
    public bool ShowInWebsite { get; set; }
    public string? Floors { get; set; }
    public sbyte RegistrarDevice { get; set; }
}
